name: Cherry pick PR

on:
  pull_request_target:
    branches:
      - main
    types: ["closed", "labeled"]

jobs:
  cherry_pick_release_v2_0:
    runs-on: ubuntu-latest
    name: Cherry pick into release-v0.2
    if: ${{ contains(github.event.pull_request.labels.*.name, 'release-v0.2') && github.event.pull_request.merged == true }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cherry pick into release-v0.2
        uses: carloscastrojumo/github-cherry-pick-action@v1.0.1
        with:
          branch: release-v0.2
          labels: |
            release-v0.2
          reviewers: |
            afritzler
          title: '[cherry-pick] {old_title}'
          body: 'Cherry picking #{old_pull_request_id} onto this branch'
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}