name: Create Release Branch

on:
  push:
    tags:
      - 'v*.*.*' # This listens to any tag with the format vX.X.X

permissions:
  contents: write

jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Set up Git
        uses: actions/checkout@v3

      - name: Extract version info from tag
        id: extract_version
        run: |
          TAG=${GITHUB_REF/refs\/tags\//}
          MAJOR=$(echo $TAG | cut -d'.' -f1 | sed 's/^v//')
          MINOR=$(echo $TAG | cut -d'.' -f2)
          PATCH=$(echo $TAG | cut -d'.' -f3)
          
          echo "::set-output name=major::$MAJOR"
          echo "::set-output name=minor::$MINOR"
          echo "::set-output name=patch::$PATCH"

      - name: Check if it is a minor or major version
        id: check_version
        run: |
          if [[ ${{ steps.extract_version.outputs.patch }} == "0" ]]; then
            echo "::set-output name=is_release::true"
          else
            echo "::set-output name=is_release::false"
          fi

      - name: Create Release Branch
        if: steps.check_version.outputs.is_release == 'true'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          
          TAG=${GITHUB_REF/refs\/tags\//}
          BRANCH_NAME="release-v${{ steps.extract_version.outputs.major }}.${{ steps.extract_version.outputs.minor }}"
          
          git checkout -b $BRANCH_NAME
          git push origin $BRANCH_NAME
